NeoBauer - solution for Ship and Cargo
Marcinati/object-oriented-programming pull request #17
Opened 2020-06-15 20:49 UTC by NeoBauer

2020-06-15 20:57 UTC, TomaszEichler submitted a review, later dismissed

2020-06-16 15:48 UTC, mateusz-talma requested changes
I think we should separate the class definitions from implementation. I would move definition to hpp file and in cpp file wrote methods.

2020-06-16 18:31 UTC, NeoBauer commented
Added .hpp files - please check, if everything is fine.

2020-06-16 18:37 UTC, mateusz-talma requested changes
Please add include hpp files in cpp

2020-06-16 18:37 UTC, mateusz-talma commented on shm/cargo.cpp
> +
Please add #include "cargo.hpp"

2020-06-16 18:37 UTC, mateusz-talma commented on shm/ship.cpp
> +        crew_ -= num;
crew_ can't be < 0

2020-06-16 21:06 UTC, mateusz-talma submitted a review, later dismissed
Please refactor operator-= for screw

2020-06-16 21:11 UTC, TomaszEichler submitted a review, later dismissed

2020-06-17 16:53 UTC, mateusz-talma commented on shm/ship.cpp
> +            return this;
You should return *this

2020-06-17 16:53 UTC, mateusz-talma commented on shm/ship.cpp
> +            return this;
You should return *this

2020-06-17 17:31 UTC, mateusz-talma commented on shm/cargo.cpp
> +        amount_ -= amount;
amount_ < 0 ?

2020-06-17 17:32 UTC, mateusz-talma commented on shm/cargo.hpp
> +#pragma once
#pragma once should be placed before any headers are included.

2020-06-17 18:33 UTC, Marcinati commented on shm/ship.cpp
> +        crew_ -= num;
done

2020-06-17 18:38 UTC, Marcinati commented on shm/cargo.cpp
> +        amount_ -= amount;
done

2020-06-17 18:38 UTC, Marcinati submitted a review, later dismissed
Everything is allrigth.

2020-06-17 18:57 UTC, Marcinati approved these changes

2020-06-17 19:00 UTC, mateusz-talma approved these changes

2020-06-17 19:00 UTC, merged